FROM ruby:2.3

RUN apt-get update -qq && \
  apt-get install -y build-essential libpq-dev nodejs less && \
  mkdir -p /usr/src/app

COPY Gemfile /usr/src/app
COPY Gemfile.lock /usr/src/app
WORKDIR /usr/src/app
RUN bundle install
COPY . /usr/src/app
ENV RAILS_SERVE_STATIC_FILES 1

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
